/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.92
 * Generated at: 2018-12-07 10:38:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.JSP;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class body_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("\r\n");
      out.write("\t<head>\r\n");
      out.write("\t\t<title>Body</title>\r\n");
      out.write("\t\t<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("\t\t<meta content=\"text/html; charset=iso-8859-2\" http-equiv=\"Content-Type\">\r\n");
      out.write("\t\t<link rel=\"stylesheet\" href=\"/FreakyShoesProj/CSSFiles/ExternalCSS.css\">\r\n");
      out.write("\t\t<style>\r\n");
      out.write("\t\t\t.mySlides {display:none;}\r\n");
      out.write("\t\t</style>\r\n");
      out.write("\t</head>\r\n");
      out.write("\r\n");
      out.write("\t<body background=\"/FreakyShoesProj/images/background.jpg\">\r\n");
      out.write("\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"images\" style=\"max-width:100%\" height=\"40%\">\r\n");
      out.write(" \t\t <a href=\"#\"><img class=\"mySlides\" src=\"/FreakyShoesProj/images/sale1.jpg\" style=\"width:100%\"></a>\r\n");
      out.write("  \t\t<a href=\"#\"><img class=\"mySlides\" src=\"/FreakyShoesProj/images/sale2.jpg\" style=\"width:100%\"></a>\r\n");
      out.write("\t\t<a href=\"#\"><img class=\"mySlides\" src=\"/FreakyShoesProj/images/sale3.jpg\" style=\"width:100%\"></a>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<script>\r\n");
      out.write("\t\t\tvar myIndex = 0;\r\n");
      out.write("\t\t\tcarousel();\r\n");
      out.write("\r\n");
      out.write("\t\t\tfunction carousel() {\r\n");
      out.write("    \t\t\tvar i;\r\n");
      out.write("   \t\t\t\t var x = document.getElementsByClassName(\"mySlides\");\r\n");
      out.write("    \t\t\tfor (i = 0; i < x.length; i++) {\r\n");
      out.write("       \t\t\t\tx[i].style.display = \"none\";  \r\n");
      out.write("    \t\t\t}\r\n");
      out.write("    \t\t\tmyIndex++;\r\n");
      out.write("    \t\t\tif (myIndex > x.length) {myIndex = 1}    \r\n");
      out.write("    \t\t\tx[myIndex-1].style.display = \"block\";  \r\n");
      out.write("    \t\t\tsetTimeout(carousel, 2000); \r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t</script>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"row\">\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<center><table border=1 >\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"#\"><img src=\"/FreakyShoesProj/images/menshoe.png\" ></a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><h6><center>Men's Section</h6></td>\r\n");
      out.write("\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t</table></center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<center><table border=1>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"#\"><img src=\"/FreakyShoesProj/images/womenshoe.png\"></a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><h6><center>Women's Section</h6></td>\r\n");
      out.write("\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t</table></center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t<div class=\"column\">\r\n");
      out.write("\t\t\t\t<center><table border=1>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><a href=\"#\"><img src=\"/FreakyShoesProj/images/kidshoe.jpg\"></a></td>\r\n");
      out.write("\t\t\t\t\t</tr>\r\n");
      out.write("\t\t\t\t\t<tr>\r\n");
      out.write("\t\t\t\t\t<td><h6><center>Kid's Section</h6></td>\r\n");
      out.write("\t\t\t\t\t</tr> \r\n");
      out.write("\t\t\t\t</table></center>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\t</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
